### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by acid-j** [REPALphilread/ReP_AL-3D-Lawn-Mower#1]
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\cwm\Desktop\Rasenmäher Roboter\ReP_AL-3D-Lawn-Mower-master\Mower Arduino Code\Mower_V5.9\MEGA_V5.9\Rain.ino:6:23: warning: unknown escape sequence: '\w'

C:\Users\cwm\Desktop\Rasenmäher Roboter\ReP_AL-3D-Lawn-Mower-master\Mower Arduino Code\Mower_V5.9\MEGA_V5.9\Volts.ino:5:28: warning: unknown escape sequence: '\j'

C:\Users\cwm\Desktop\Rasenmäher Roboter\ReP_AL-3D-Lawn-Mower-master\Mower Arduino Code\Mower_V5.9\MEGA_V5.9\Volts.ino:68:24: warning: unknown escape sequence: '\q'

C:\Users\cwm\Desktop\Rasenmäher Roboter\ReP_AL-3D-Lawn-Mower-master\Mower Arduino Code\Mower_V5.9\MEGA_V5.9\MEGA_V5.9.ino: In function 'void setup()':

MEGA_V5.9:328:3: error: 'Serial1' was not declared in this scope

C:\Users\cwm\Desktop\Rasenmäher Roboter\ReP_AL-3D-Lawn-Mower-master\Mower Arduino Code\Mower_V5.9\MEGA_V5.9\Rain.ino: In function 'void Check_if_Raining_From_Nano()':

Rain:6:6: error: 'Serial1' was not declared in this scope

exit status 1
'Serial1' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by REPALphilread** [comment]
You need to compile for the Arduino MEGA.   Not the UNO
